DEBUG: true
advanced:
  J_epsilon_rate: 0.001
  TVLoss_weight: 0.0001
  dimesions: 10
  grad_clip: true
  limit_output_range: true
  max_norm: 0.0001
  output_lower_limit: 1
  output_upper_limit: 2.6
  phy_loss_rate: 1.0e-07
  pos_encoding: true
  fig_save_interval: 100
enable_wandb: false
experiment:
  baseline: Es_xy_to_J
  channels: [0]
  image_input: true
  loss_terms:
    J_loss: true
    TV_loss: false
    phy_loss: true
    second_derivative_loss: false
  supervise: J_epsilon
  test_noise_ratio: 0.05
  train_noise_ratio: 0.05
global:
  experiment_name: mnist_noise05
  fig_path: ./fig/{experiment_name}
  model_save_path: ./model/{experiment_name}
  test_dataset_path: ./data/test/mnist/mnist_test.pkl
  train_dataset_path: ./data/train/MNIST_train/MNIST_train.pkl
model:
  D: 8
  W: 256
  skips: []
  epsilon_output: false
  output_rate: 0.05
training:
  BATCH_SIZE: 32
  LEARNING_RATE: 0.001
  gamma: 0.8
  lr_decrease: false
  num_epochs: 300
  save_interval: 20
  step_size: 10
